/**
* Signal Strength
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Strength_output.h
 *
 * 
 */

#ifndef Strength_output_H_
#define Strength_output_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Strength_output
{
public:
    Strength_output();
    virtual ~Strength_output();

    void validate();

    /////////////////////////////////////////////
    /// Strength_output members

    /// <summary>
    /// 
    /// </summary>
    int32_t getActual() const;
    void setActual(int32_t const value);
    bool actualIsSet() const;
    void unsetActual();
    /// <summary>
    /// 
    /// </summary>
    int32_t getExpected() const;
    void setExpected(int32_t const value);
    bool expectedIsSet() const;
    void unsetExpected();
    /// <summary>
    /// 
    /// </summary>
    double getStrength() const;
    void setStrength(double const value);
    bool strengthIsSet() const;
    void unsetStrength();

    friend void to_json(nlohmann::json& j, const Strength_output& o);
    friend void from_json(const nlohmann::json& j, Strength_output& o);
protected:
    int32_t m_Actual;
    bool m_ActualIsSet;
    int32_t m_Expected;
    bool m_ExpectedIsSet;
    double m_Strength;
    bool m_StrengthIsSet;
};

}
}
}
}

#endif /* Strength_output_H_ */
