/**
* Signal Strength
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Strength_input.h
 *
 * 
 */

#ifndef Strength_input_H_
#define Strength_input_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Strength_input
{
public:
    Strength_input();
    virtual ~Strength_input();

    void validate();

    /////////////////////////////////////////////
    /// Strength_input members

    /// <summary>
    /// 
    /// </summary>
    int32_t getActual() const;
    void setActual(int32_t const value);
    bool actualIsSet() const;
    void unsetActual();
    /// <summary>
    /// 
    /// </summary>
    int32_t getExpected() const;
    void setExpected(int32_t const value);
    bool expectedIsSet() const;
    void unsetExpected();

    friend void to_json(nlohmann::json& j, const Strength_input& o);
    friend void from_json(const nlohmann::json& j, Strength_input& o);
protected:
    int32_t m_Actual;
    bool m_ActualIsSet;
    int32_t m_Expected;
    bool m_ExpectedIsSet;
};

}
}
}
}

#endif /* Strength_input_H_ */
