/**
* Signal Strength
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Strength_input.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Strength_input::Strength_input()
{
    m_Actual = 0;
    m_ActualIsSet = false;
    m_Expected = 0;
    m_ExpectedIsSet = false;
    
}

Strength_input::~Strength_input()
{
}

void Strength_input::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Strength_input& o)
{
    j = nlohmann::json();
    if(o.actualIsSet())
        j["actual"] = o.m_Actual;
    if(o.expectedIsSet())
        j["expected"] = o.m_Expected;
}

void from_json(const nlohmann::json& j, Strength_input& o)
{
    if(j.find("actual") != j.end())
    {
        j.at("actual").get_to(o.m_Actual);
        o.m_ActualIsSet = true;
    } 
    if(j.find("expected") != j.end())
    {
        j.at("expected").get_to(o.m_Expected);
        o.m_ExpectedIsSet = true;
    } 
}

int32_t Strength_input::getActual() const
{
    return m_Actual;
}
void Strength_input::setActual(int32_t const value)
{
    m_Actual = value;
    m_ActualIsSet = true;
}
bool Strength_input::actualIsSet() const
{
    return m_ActualIsSet;
}
void Strength_input::unsetActual()
{
    m_ActualIsSet = false;
}
int32_t Strength_input::getExpected() const
{
    return m_Expected;
}
void Strength_input::setExpected(int32_t const value)
{
    m_Expected = value;
    m_ExpectedIsSet = true;
}
bool Strength_input::expectedIsSet() const
{
    return m_ExpectedIsSet;
}
void Strength_input::unsetExpected()
{
    m_ExpectedIsSet = false;
}

}
}
}
}

