/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "MathApiImpl.h"
#include <math.h>
#include "json.hpp"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

MathApiImpl::MathApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : MathApi(rtr)
    { }

void MathApiImpl::math_sqrt(const Sqrt_input &body, Pistache::Http::ResponseWriter &response) {
    double x;
    double result;
    
    Sqrt_output::Sqrt_output output;
    nlohmann::json outputjson;
    
    x = body.getX();
    result = sqrt(x);
    output.setX(x);
    output.setResult(result);
    to_json(outputjson, output);
    response.send(Pistache::Http::Code::Ok, outputjson.dump());
}

}
}
}
}

