/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* MathApiImpl.h
*
* 
*/

#ifndef MATH_API_IMPL_H_
#define MATH_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <MathApi.h>

#include <pistache/optional.h>

#include "Sqrt_input.h"
#include "Sqrt_output.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class MathApiImpl : public org::openapitools::server::api::MathApi {
public:
    MathApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~MathApiImpl() {}

    void math_sqrt(const Sqrt_input &body, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif