/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Sqrt_output.h
 *
 * 
 */

#ifndef Sqrt_output_H_
#define Sqrt_output_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Sqrt_output
{
public:
    Sqrt_output();
    virtual ~Sqrt_output();

    void validate();

    /////////////////////////////////////////////
    /// Sqrt_output members

    /// <summary>
    /// 
    /// </summary>
    double getX() const;
    void setX(double const value);
    bool XIsSet() const;
    void unsetx();
    /// <summary>
    /// 
    /// </summary>
    double getResult() const;
    void setResult(double const value);
    bool resultIsSet() const;
    void unsetResult();

    friend void to_json(nlohmann::json& j, const Sqrt_output& o);
    friend void from_json(const nlohmann::json& j, Sqrt_output& o);
protected:
    double m_x;
    bool m_xIsSet;
    double m_Result;
    bool m_ResultIsSet;
};

}
}
}
}

#endif /* Sqrt_output_H_ */
