/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "MathApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

MathApi::MathApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
}

void MathApi::init() {
    setupRoutes();
}

void MathApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/sqrt", Routes::bind(&MathApi::math_sqrt_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&MathApi::math_api_default_handler, this));
}

void MathApi::math_sqrt_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the body param
    
    Sqrt_input body;
    
    try {
      nlohmann::json::parse(request.body()).get_to(body);
      this->math_sqrt(body, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}

void MathApi::math_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

