/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * MathApi.h
 *
 * 
 */

#ifndef MathApi_H_
#define MathApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "Sqrt_input.h"
#include "Sqrt_output.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  MathApi {
public:
    MathApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~MathApi() {}
    void init();

    const std::string base = "/v2";

private:
    void setupRoutes();

    void math_sqrt_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void math_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="body"> (optional)</param>
    virtual void math_sqrt(const Sqrt_input &body, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* MathApi_H_ */

